<?php

namespace Database\Seeders;

use App\Models\OrganizerPayoutMethod;
use App\Models\OrganizerProfile;
use Illuminate\Database\Seeder;

class OrganizerPayoutMethodSeeder extends Seeder
{
    public function run(): void
    {
        $organizer = OrganizerProfile::query()
            ->where('status', OrganizerProfile::STATUS_APPROVED)
            ->orderBy('id')
            ->first();

        if (! $organizer) {
            return;
        }

        OrganizerPayoutMethod::query()->updateOrCreate(
            ['organizer_profile_id' => $organizer->id],
            [
                'method_type' => OrganizerPayoutMethod::METHOD_BANK,
                'status' => OrganizerPayoutMethod::STATUS_VERIFIED,
                'is_active' => true,
                'requires_verification' => true,
                'currency' => 'BDT',
                'account_holder_name' => $organizer->organization_name ?: 'Demo Organizer Account',
                'bank_name' => 'Demo Marketplace Bank',
                'branch_name' => 'Main Branch',
                'account_number' => '1234567890',
                'routing_number' => '000111222',
                'mobile_wallet_provider' => null,
                'mobile_wallet_number' => null,
                'organizer_note' => 'Verified demo payout method generated by seeder.',
                'admin_note' => 'Seeder verified payout method for local testing.',
                'reviewed_by' => null,
                'submitted_at' => now(),
                'reviewed_at' => now(),
            ]
        );
    }
}
